### ISSUE TITLE
Doc is misleading

### ISSUE THREAD

**Issue by marcandre** [Multiverse-io/eextoheex#6]
First, thanks for the great script, much appreciated.

The doc states "This gives the wrong result when `@foo` is not a string". That sentence is inaccurate. This gives a different result only for 3 values: if `@foo` is `true`, `false` (values that are typically incorrect), or `nil` (where removing the attribute completely has typically the same effect or is better).

It was easy to modify the code to output the simplified version. Let me know if I can help with a PR so that the official repo offers that possibility, otherwise we'll use [our fork](https://github.com/super-seguros/eextoheex).

Feel free to close this if you don't want to tweak the language 😄

**Comment by addrummond** [comment]
Hi Marc-André. I understand the impetus to make this change, but I chose to use the longer `{"#{ ... }"}` form because it avoided generating incorrect output for some real instances in our codebase. I don't remember the details of all of these, but there were cases for example where we relied on `false -> `"false"` for an attribute that was parsed as JSON. (Ugly code, no doubt!) In my view it is not worth it to sacrifice correctness for more beautiful output. However, I can see why others would not agree in this case, so I will add link to your fork from the Readme. 

I had previously considered outputting the shorter form just when the attribute is in a restricted list of attributes where it is virtually certain that the difference will not matter (e.g. `class`, `style`, etc.) I would accept a PR along those lines.

I see your point about the docs. I will update them to mention the specific values that cause incorrect output.

**Comment by marcandre** [comment]
Right, or `data-` parameters would get the strict conversion, others would not. Or were you using other parameters than `data-something`?

**Comment by addrummond** [comment]
Yeah, I think that would make sense. Possibly it should also exclude `value`, since I guess `<input ... value="false">` might sometimes not be equivalent to `<input ...>`.

**Comment by marcandre** [comment]
Good point about `value` 👍

**Comment by addrummond** [comment]
I am closing this issue because the issue with the docs has been fixed. Still happy to consider a PR along the lines discussed above.
